services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    # environment:
      #- FLASK_APP=app.py
    command: gunicorn -w 4 -b 0.0.0.0:5001 app:app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: eventdb
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
